[2024-12-30 15:49:51,048] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_catchup_and_backfill_v1.task1 manual__2024-12-30T15:49:50.408874+00:00 [queued]>
[2024-12-30 15:49:51,055] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_catchup_and_backfill_v1.task1 manual__2024-12-30T15:49:50.408874+00:00 [queued]>
[2024-12-30 15:49:51,055] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-30 15:49:51,055] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2024-12-30 15:49:51,055] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-30 15:49:51,066] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): task1> on 2024-12-30 15:49:50.408874+00:00
[2024-12-30 15:49:51,069] {standard_task_runner.py:52} INFO - Started process 273 to run task
[2024-12-30 15:49:51,071] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test_dag_catchup_and_backfill_v1', 'task1', 'manual__2024-12-30T15:49:50.408874+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpe8c61vq6', '--error-file', '/tmp/tmpova2s49e']
[2024-12-30 15:49:51,072] {standard_task_runner.py:80} INFO - Job 8: Subtask task1
[2024-12-30 15:49:51,111] {task_command.py:370} INFO - Running <TaskInstance: test_dag_catchup_and_backfill_v1.task1 manual__2024-12-30T15:49:50.408874+00:00 [running]> on host 3ce865646fe0
[2024-12-30 15:49:51,160] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=swetansu
AIRFLOW_CTX_DAG_ID=test_dag_catchup_and_backfill_v1
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2024-12-30T15:49:50.408874+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-30T15:49:50.408874+00:00
[2024-12-30 15:49:51,160] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-30 15:49:51,161] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo test_catchup']
[2024-12-30 15:49:51,167] {subprocess.py:85} INFO - Output:
[2024-12-30 15:49:51,169] {subprocess.py:92} INFO - test_catchup
[2024-12-30 15:49:51,169] {subprocess.py:96} INFO - Command exited with return code 0
[2024-12-30 15:49:51,188] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test_dag_catchup_and_backfill_v1, task_id=task1, execution_date=20241230T154950, start_date=20241230T154951, end_date=20241230T154951
[2024-12-30 15:49:51,203] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-12-30 15:49:51,225] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
